# ========================================
#  Test GET /api/products - Active Products
# ========================================
@EcommerceApi_HostAddress = https://localhost:7216

GET {{EcommerceApi_HostAddress}}/api/products
Accept: application/json
Content-Type: application/json

###